// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	user "Meeting/apps/user/api/internal/handler/user"
	userinfo "Meeting/apps/user/api/internal/handler/userinfo"
	"Meeting/apps/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登入
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 下线
				Method:  http.MethodGet,
				Path:    "/offline",
				Handler: userinfo.OfflineHandler(serverCtx),
			},
			{
				// ping
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: userinfo.PingHandler(serverCtx),
			},
			{
				// 更新信息
				Method:  http.MethodPost,
				Path:    "/updateInfo",
				Handler: userinfo.UpdateInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
