// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string     `json:"token"`
	User  UserEntity `json:"user"`
}

type RegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type RegisterResp struct {
}

type UserEntity struct {
	UserId            string `json:"userId"`
	Phone             string `json:"phone"`
	NickName          string `json:"nickName"`
	Sex               int    `json:"sex"`
	PersonalSignature string `json:"personalSignature"`
	CreateTime        int64  `json:"createTime"`
	AreaName          string `json:"areaName"`
	AreaCode          string `json:"areaCode"`
}

type UpdateInfoReq struct {
	User UserEntity `json:"user"`
}

type UpdateInfoResp struct {
	User UserEntity `json:"user"`
}
