// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: apps/meeting/rpc/meeting.proto

package meeting

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Meeting_CreateMeeting_FullMethodName  = "/meeting.Meeting/CreateMeeting"
	Meeting_JoinMeeting_FullMethodName    = "/meeting.Meeting/JoinMeeting"
	Meeting_HistoryMeeting_FullMethodName = "/meeting.Meeting/HistoryMeeting"
)

// MeetingClient is the client API for Meeting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeetingClient interface {
	CreateMeeting(ctx context.Context, in *CreateMeetingReq, opts ...grpc.CallOption) (*CreateMeetingResp, error)
	JoinMeeting(ctx context.Context, in *JoinMeetingReq, opts ...grpc.CallOption) (*JoinMeetingResp, error)
	HistoryMeeting(ctx context.Context, in *HistoryMeetingReq, opts ...grpc.CallOption) (*HistoryMeetingResp, error)
}

type meetingClient struct {
	cc grpc.ClientConnInterface
}

func NewMeetingClient(cc grpc.ClientConnInterface) MeetingClient {
	return &meetingClient{cc}
}

func (c *meetingClient) CreateMeeting(ctx context.Context, in *CreateMeetingReq, opts ...grpc.CallOption) (*CreateMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMeetingResp)
	err := c.cc.Invoke(ctx, Meeting_CreateMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingClient) JoinMeeting(ctx context.Context, in *JoinMeetingReq, opts ...grpc.CallOption) (*JoinMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinMeetingResp)
	err := c.cc.Invoke(ctx, Meeting_JoinMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingClient) HistoryMeeting(ctx context.Context, in *HistoryMeetingReq, opts ...grpc.CallOption) (*HistoryMeetingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryMeetingResp)
	err := c.cc.Invoke(ctx, Meeting_HistoryMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeetingServer is the server API for Meeting service.
// All implementations must embed UnimplementedMeetingServer
// for forward compatibility.
type MeetingServer interface {
	CreateMeeting(context.Context, *CreateMeetingReq) (*CreateMeetingResp, error)
	JoinMeeting(context.Context, *JoinMeetingReq) (*JoinMeetingResp, error)
	HistoryMeeting(context.Context, *HistoryMeetingReq) (*HistoryMeetingResp, error)
	mustEmbedUnimplementedMeetingServer()
}

// UnimplementedMeetingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeetingServer struct{}

func (UnimplementedMeetingServer) CreateMeeting(context.Context, *CreateMeetingReq) (*CreateMeetingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMeeting not implemented")
}
func (UnimplementedMeetingServer) JoinMeeting(context.Context, *JoinMeetingReq) (*JoinMeetingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinMeeting not implemented")
}
func (UnimplementedMeetingServer) HistoryMeeting(context.Context, *HistoryMeetingReq) (*HistoryMeetingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryMeeting not implemented")
}
func (UnimplementedMeetingServer) mustEmbedUnimplementedMeetingServer() {}
func (UnimplementedMeetingServer) testEmbeddedByValue()                 {}

// UnsafeMeetingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeetingServer will
// result in compilation errors.
type UnsafeMeetingServer interface {
	mustEmbedUnimplementedMeetingServer()
}

func RegisterMeetingServer(s grpc.ServiceRegistrar, srv MeetingServer) {
	// If the following call pancis, it indicates UnimplementedMeetingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Meeting_ServiceDesc, srv)
}

func _Meeting_CreateMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServer).CreateMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meeting_CreateMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServer).CreateMeeting(ctx, req.(*CreateMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meeting_JoinMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServer).JoinMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meeting_JoinMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServer).JoinMeeting(ctx, req.(*JoinMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meeting_HistoryMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryMeetingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServer).HistoryMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meeting_HistoryMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServer).HistoryMeeting(ctx, req.(*HistoryMeetingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Meeting_ServiceDesc is the grpc.ServiceDesc for Meeting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Meeting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meeting.Meeting",
	HandlerType: (*MeetingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMeeting",
			Handler:    _Meeting_CreateMeeting_Handler,
		},
		{
			MethodName: "JoinMeeting",
			Handler:    _Meeting_JoinMeeting_Handler,
		},
		{
			MethodName: "HistoryMeeting",
			Handler:    _Meeting_HistoryMeeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/meeting/rpc/meeting.proto",
}
