// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: apps/meeting/rpc/meeting.proto

package meeting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeetingEntity struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MeetingId       string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	MeetingName     string                 `protobuf:"bytes,2,opt,name=meetingName,proto3" json:"meetingName,omitempty"`
	MeetingPassword string                 `protobuf:"bytes,3,opt,name=meetingPassword,proto3" json:"meetingPassword,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	HostId          string                 `protobuf:"bytes,5,opt,name=hostId,proto3" json:"hostId,omitempty"`
	HostName        string                 `protobuf:"bytes,6,opt,name=hostName,proto3" json:"hostName,omitempty"`
	StartTime       int64                  `protobuf:"varint,7,opt,name=startTime,proto3" json:"startTime,omitempty"` // 时间戳
	EndTime         int64                  `protobuf:"varint,8,opt,name=endTime,proto3" json:"endTime,omitempty"`     // 时间戳
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeetingEntity) Reset() {
	*x = MeetingEntity{}
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingEntity) ProtoMessage() {}

func (x *MeetingEntity) ProtoReflect() protoreflect.Message {
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingEntity.ProtoReflect.Descriptor instead.
func (*MeetingEntity) Descriptor() ([]byte, []int) {
	return file_apps_meeting_rpc_meeting_proto_rawDescGZIP(), []int{0}
}

func (x *MeetingEntity) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *MeetingEntity) GetMeetingName() string {
	if x != nil {
		return x.MeetingName
	}
	return ""
}

func (x *MeetingEntity) GetMeetingPassword() string {
	if x != nil {
		return x.MeetingPassword
	}
	return ""
}

func (x *MeetingEntity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MeetingEntity) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *MeetingEntity) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *MeetingEntity) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MeetingEntity) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type CreateMeetingReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MeetingName     string                 `protobuf:"bytes,1,opt,name=meetingName,proto3" json:"meetingName,omitempty"`
	HostName        string                 `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MeetingPassword string                 `protobuf:"bytes,4,opt,name=meetingPassword,proto3" json:"meetingPassword,omitempty"`
	HostId          string                 `protobuf:"bytes,5,opt,name=hostId,proto3" json:"hostId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateMeetingReq) Reset() {
	*x = CreateMeetingReq{}
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingReq) ProtoMessage() {}

func (x *CreateMeetingReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingReq.ProtoReflect.Descriptor instead.
func (*CreateMeetingReq) Descriptor() ([]byte, []int) {
	return file_apps_meeting_rpc_meeting_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMeetingReq) GetMeetingName() string {
	if x != nil {
		return x.MeetingName
	}
	return ""
}

func (x *CreateMeetingReq) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *CreateMeetingReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMeetingReq) GetMeetingPassword() string {
	if x != nil {
		return x.MeetingPassword
	}
	return ""
}

func (x *CreateMeetingReq) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type CreateMeetingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *MeetingEntity         `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeetingResp) Reset() {
	*x = CreateMeetingResp{}
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingResp) ProtoMessage() {}

func (x *CreateMeetingResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingResp.ProtoReflect.Descriptor instead.
func (*CreateMeetingResp) Descriptor() ([]byte, []int) {
	return file_apps_meeting_rpc_meeting_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMeetingResp) GetInfo() *MeetingEntity {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *CreateMeetingResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HistoryMeetingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryMeetingReq) Reset() {
	*x = HistoryMeetingReq{}
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryMeetingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryMeetingReq) ProtoMessage() {}

func (x *HistoryMeetingReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryMeetingReq.ProtoReflect.Descriptor instead.
func (*HistoryMeetingReq) Descriptor() ([]byte, []int) {
	return file_apps_meeting_rpc_meeting_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryMeetingReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type HistoryMeetingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MeetingEntity       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryMeetingResp) Reset() {
	*x = HistoryMeetingResp{}
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryMeetingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryMeetingResp) ProtoMessage() {}

func (x *HistoryMeetingResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryMeetingResp.ProtoReflect.Descriptor instead.
func (*HistoryMeetingResp) Descriptor() ([]byte, []int) {
	return file_apps_meeting_rpc_meeting_proto_rawDescGZIP(), []int{4}
}

func (x *HistoryMeetingResp) GetList() []*MeetingEntity {
	if x != nil {
		return x.List
	}
	return nil
}

type JoinMeetingReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MeetingId       string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName        string                 `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	MeetingPassword string                 `protobuf:"bytes,4,opt,name=meetingPassword,proto3" json:"meetingPassword,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JoinMeetingReq) Reset() {
	*x = JoinMeetingReq{}
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMeetingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMeetingReq) ProtoMessage() {}

func (x *JoinMeetingReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMeetingReq.ProtoReflect.Descriptor instead.
func (*JoinMeetingReq) Descriptor() ([]byte, []int) {
	return file_apps_meeting_rpc_meeting_proto_rawDescGZIP(), []int{5}
}

func (x *JoinMeetingReq) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *JoinMeetingReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinMeetingReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *JoinMeetingReq) GetMeetingPassword() string {
	if x != nil {
		return x.MeetingPassword
	}
	return ""
}

type JoinMeetingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMeetingResp) Reset() {
	*x = JoinMeetingResp{}
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMeetingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMeetingResp) ProtoMessage() {}

func (x *JoinMeetingResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_meeting_rpc_meeting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMeetingResp.ProtoReflect.Descriptor instead.
func (*JoinMeetingResp) Descriptor() ([]byte, []int) {
	return file_apps_meeting_rpc_meeting_proto_rawDescGZIP(), []int{6}
}

func (x *JoinMeetingResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_apps_meeting_rpc_meeting_proto protoreflect.FileDescriptor

const file_apps_meeting_rpc_meeting_proto_rawDesc = "" +
	"\n" +
	"\x1eapps/meeting/rpc/meeting.proto\x12\ameeting\"\x87\x02\n" +
	"\rMeetingEntity\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\x12 \n" +
	"\vmeetingName\x18\x02 \x01(\tR\vmeetingName\x12(\n" +
	"\x0fmeetingPassword\x18\x03 \x01(\tR\x0fmeetingPassword\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06hostId\x18\x05 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostName\x18\x06 \x01(\tR\bhostName\x12\x1c\n" +
	"\tstartTime\x18\a \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\b \x01(\x03R\aendTime\"\xb4\x01\n" +
	"\x10CreateMeetingReq\x12 \n" +
	"\vmeetingName\x18\x01 \x01(\tR\vmeetingName\x12\x1a\n" +
	"\bhostName\x18\x02 \x01(\tR\bhostName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12(\n" +
	"\x0fmeetingPassword\x18\x04 \x01(\tR\x0fmeetingPassword\x12\x16\n" +
	"\x06hostId\x18\x05 \x01(\tR\x06hostId\"U\n" +
	"\x11CreateMeetingResp\x12*\n" +
	"\x04info\x18\x01 \x01(\v2\x16.meeting.MeetingEntityR\x04info\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"+\n" +
	"\x11HistoryMeetingReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x12HistoryMeetingResp\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.meeting.MeetingEntityR\x04list\"\x8c\x01\n" +
	"\x0eJoinMeetingReq\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\x12(\n" +
	"\x0fmeetingPassword\x18\x04 \x01(\tR\x0fmeetingPassword\"'\n" +
	"\x0fJoinMeetingResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xde\x01\n" +
	"\aMeeting\x12F\n" +
	"\rCreateMeeting\x12\x19.meeting.CreateMeetingReq\x1a\x1a.meeting.CreateMeetingResp\x12@\n" +
	"\vJoinMeeting\x12\x17.meeting.JoinMeetingReq\x1a\x18.meeting.JoinMeetingResp\x12I\n" +
	"\x0eHistoryMeeting\x12\x1a.meeting.HistoryMeetingReq\x1a\x1b.meeting.HistoryMeetingRespB\vZ\t./meetingb\x06proto3"

var (
	file_apps_meeting_rpc_meeting_proto_rawDescOnce sync.Once
	file_apps_meeting_rpc_meeting_proto_rawDescData []byte
)

func file_apps_meeting_rpc_meeting_proto_rawDescGZIP() []byte {
	file_apps_meeting_rpc_meeting_proto_rawDescOnce.Do(func() {
		file_apps_meeting_rpc_meeting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_meeting_rpc_meeting_proto_rawDesc), len(file_apps_meeting_rpc_meeting_proto_rawDesc)))
	})
	return file_apps_meeting_rpc_meeting_proto_rawDescData
}

var file_apps_meeting_rpc_meeting_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_apps_meeting_rpc_meeting_proto_goTypes = []any{
	(*MeetingEntity)(nil),      // 0: meeting.MeetingEntity
	(*CreateMeetingReq)(nil),   // 1: meeting.CreateMeetingReq
	(*CreateMeetingResp)(nil),  // 2: meeting.CreateMeetingResp
	(*HistoryMeetingReq)(nil),  // 3: meeting.HistoryMeetingReq
	(*HistoryMeetingResp)(nil), // 4: meeting.HistoryMeetingResp
	(*JoinMeetingReq)(nil),     // 5: meeting.JoinMeetingReq
	(*JoinMeetingResp)(nil),    // 6: meeting.JoinMeetingResp
}
var file_apps_meeting_rpc_meeting_proto_depIdxs = []int32{
	0, // 0: meeting.CreateMeetingResp.info:type_name -> meeting.MeetingEntity
	0, // 1: meeting.HistoryMeetingResp.list:type_name -> meeting.MeetingEntity
	1, // 2: meeting.Meeting.CreateMeeting:input_type -> meeting.CreateMeetingReq
	5, // 3: meeting.Meeting.JoinMeeting:input_type -> meeting.JoinMeetingReq
	3, // 4: meeting.Meeting.HistoryMeeting:input_type -> meeting.HistoryMeetingReq
	2, // 5: meeting.Meeting.CreateMeeting:output_type -> meeting.CreateMeetingResp
	6, // 6: meeting.Meeting.JoinMeeting:output_type -> meeting.JoinMeetingResp
	4, // 7: meeting.Meeting.HistoryMeeting:output_type -> meeting.HistoryMeetingResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apps_meeting_rpc_meeting_proto_init() }
func file_apps_meeting_rpc_meeting_proto_init() {
	if File_apps_meeting_rpc_meeting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_meeting_rpc_meeting_proto_rawDesc), len(file_apps_meeting_rpc_meeting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_meeting_rpc_meeting_proto_goTypes,
		DependencyIndexes: file_apps_meeting_rpc_meeting_proto_depIdxs,
		MessageInfos:      file_apps_meeting_rpc_meeting_proto_msgTypes,
	}.Build()
	File_apps_meeting_rpc_meeting_proto = out.File
	file_apps_meeting_rpc_meeting_proto_goTypes = nil
	file_apps_meeting_rpc_meeting_proto_depIdxs = nil
}
