// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	meeting "Meeting/apps/meeting/api/internal/handler/meeting"
	"Meeting/apps/meeting/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建会议
				Method:  http.MethodPost,
				Path:    "/createMeeting",
				Handler: meeting.CreateMeetingHandler(serverCtx),
			},
			{
				// 历史会议
				Method:  http.MethodPost,
				Path:    "/historyMeeting",
				Handler: meeting.HistoryMeetingHandler(serverCtx),
			},
			{
				// 加入会议
				Method:  http.MethodPost,
				Path:    "/joinMeeting",
				Handler: meeting.JoinMeetingHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
