// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type GetSignatureReq struct {
}

type GetSignatureResp struct {
	Data PolicyToken `json:"data"`
}

type PolicyToken struct {
	Policy           string `json:"policy"`
	SecurityToken    string `json:"security_token"`
	SignatureVersion string `json:"x_oss_signature_version"`
	Credential       string `json:"x_oss_credential"`
	Date             string `json:"x_oss_date"`
	Signature        string `json:"signature"`
	Host             string `json:"host"`
	Dir              string `json:"dir"`
}
