// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CreateMeetingReq struct {
	MeetingName     string `json:"meetingName"`
	Description     string `json:"description"`
	MeetingPassword string `json:"meetingPassword"`
	HostId          string `json:"hostId"`
	HostName        string `json:"hostName"`
}

type CreateMeetingResp struct {
	Info  MeetingEntity `json:"info"`
	Token string        `json:"token"`
}

type HistoryMeetingReq struct {
	UserId string `json:"userId"`
}

type HistoryMeetingResp struct {
	List []*MeetingEntity `json:"list"`
}

type JoinMeetingReq struct {
	MeetingId       string `json:"meetingId"`
	UserId          string `json:"userId"`
	UserName        string `json:"userName"`
	MeetingPassword string `json:"meetingPassword"`
}

type JoinMeetingResp struct {
	Token string `json:"token"`
}

type MeetingEntity struct {
	MeetingId   string `json:"meetingId"`
	MeetingName string `json:"meetingName"`
	Description string `json:"description"`
	HostId      string `json:"hostId"`
	HostName    string `json:"hostName"`
	StartTime   int64  `json:"startTime"`
	EndTime     int64  `json:"endTime"`
}

type SingleMember struct {
	Uid  string `json:"uid"`
	Name string `json:"name"`
}
