// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package server

import (
	"context"

	"Meeting/apps/user/rpc/internal/logic"
	"Meeting/apps/user/rpc/internal/svc"
	"Meeting/apps/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) UpdateInfo(ctx context.Context, in *user.UpdateInfoReq) (*user.UpdateInfoResp, error) {
	l := logic.NewUpdateInfoLogic(ctx, s.svcCtx)
	return l.UpdateInfo(in)
}

func (s *UserServer) Ping(ctx context.Context, in *user.PingReq) (*user.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserServer) Offline(ctx context.Context, in *user.PingReq) (*user.PingResp, error) {
	l := logic.NewOfflineLogic(ctx, s.svcCtx)
	return l.Offline(in)
}
